FROM nginx:alpine

# Copiar arquivos do frontend
COPY . /usr/share/nginx/html

# Configurar nginx para SPA
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]