[phases.setup]
nixPkgs = ['nodejs_18']
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']

[phases.install]
dependsOn = ['setup']
cmds = [
  'cd backend',
  'npm ci'
]

[phases.build]
dependsOn = ['install']
cmds = [
  'cd backend',
  'npm run migrate || true'
]

[start]
cmd = 'cd backend && npm start'
